### ISSUE TITLE
Add negation to Filters

### ISSUE THREAD

**Issue by pablomayobre** [Keyslam-Group/Concord#32]
The idea is that Pool Filters should be able to reject an Entity if it has a given Component.

I already have this working in [`a00ee08`](https://github.com/pablomayobre/Concord/commit/a00ee0821d83ff183baf863260f759c3b63522a5)

**Comment by HDictus** [comment]
Hi Pablo, I've been enjoying this feature. Can I ask why you haven't made a pull request into the main Concord repo with this?

**Comment by pablomayobre** [comment]
This feature exists in the [dev branch][dev] and also in the [experimental branch][experimental].

Right now I want people to test and try to find bugs in the [experimental branch][experimental] so that I can confirm that the code is proof tested, and ready to be merged into [dev][dev]. Once that's ready I would love to have up to date documentation, and once we have that, then it can move into master and [4.0](https://github.com/Tjakka5/Concord/milestone/1) can be released.

Right now [dev][dev] is usable, without major bugs or errors, just lacking up-to-date documentation. While [experimental][experimental] can have bugs or errors and lacks far more documentation.

[experimental]: https://github.com/Tjakka5/Concord/tree/experimental
[dev]: https://github.com/Tjakka5/Concord/tree/dev
