### ISSUE TITLE
Sorting Pools

### ISSUE THREAD

**Issue by pablomayobre** [Keyslam-Group/Concord#33]
Sorting Pools before looping through the Entities could be useful for rendering and collision checks.

The feature can be easily added to Lists and Pools would inherit it.

I have already implemented this at [`a00ee08`](https://github.com/pablomayobre/Concord/commit/a00ee0821d83ff183baf863260f759c3b63522a5)

**Comment by chicogamedev** [comment]
Hi, where is it possible to see an exemple on how to use this ? The main read-me do not talk about this amazing feature.

Thanks for the amazing library.

**Comment by pablomayobre** [comment]
Yes, this can already be used in the [`dev`](https://github.com/Tjakka5/Concord/tree/dev) branch. It's really simple to use:

```lua
function RenderSystem:draw () --An event in one of your systems

   --self.pool is the Pool we want to sort
   self.pool:sort(function (e1, e2)
      return e1.zindex > e2.zindex
   end)
   
   -- Your renderer code goes here

end
```

The sort function has the same signature as [`table.sort`](http://www.lua.org/manual/5.1/manual.html#pdf-table.sort) (since that's used internally)

**Comment by chicogamedev** [comment]
Thanks, amazing !

When will this be available in the stable branch ?


Thanks

**Comment by pablomayobre** [comment]
Once we complete the 4.0 Milestone, we will do a big release. It will probably happen this month, since most of those features are already implemented, and only Entity IDs (#38) and World:query (#44) are missing.

If you are watching the repository, you will most likely receive a notification on the new release, otherwise you can jump over to our [Discord server](https://discord.gg/zNP7GxYSnf) to get notified once the new version is announced.

**Comment by leeserlionel** [comment]
> Yes, this can already be used in the [`dev`](https://github.com/Tjakka5/Concord/tree/dev) branch. It's really simple to use:
> 
> ```lua
> function RenderSystem:draw () --An event in one of your systems
> 
>    --self.pool is the Pool we want to sort
>    self.pool:sort(function (e1, e2)
>       return e1.zindex > e2.zindex
>    end)
>    
>    -- Your renderer code goes here
> 
> end
> ```
> 

Just a little question, what does e1 and e2 stand for ? I just can't understand how this work. 
What should I give to the function. 

Thanks for your time.

**Comment by chicogamedev** [comment]
> Yes, this can already be used in the [`dev`](https://github.com/Tjakka5/Concord/tree/dev) branch. It's really simple to use:
> 
> ```lua
> function RenderSystem:draw () --An event in one of your systems
> 
>    --self.pool is the Pool we want to sort
>    self.pool:sort(function (e1, e2)
>       return e1.zindex > e2.zindex
>    end)
>    
>    -- Your renderer code goes here
> 
> end
> ```

Hello,

Just one quick question about this exemple. What does e1 and e2 stands for? I just can't wrap my head around the way this sort actually works.

Thanks

**Comment by flamendless** [comment]
e1 and e2 are the entities in the pool that are currently to be sorted

**Comment by chicogamedev** [comment]
Ah ok,

I thought that was something I need to replace.

Thanks for your answer.

**Comment by pablomayobre** [comment]
As said in my original comment, it works the same way as [`table.sort`](http://www.lua.org/manual/5.1/manual.html#pdf-table.sort). In the sorting function (also called order function) receive two elements (in this case two Entities) of the Pool and you need to compare them and return a `true`/`false` value.

If you return `true` then the first element will appear before the second element.
If you return `false` then the second element will appear before the first element.

**Comment by chicogamedev** [comment]
Indeed I should have made a bit of research before asking.

Is there any performances drawbacks to sort pools right in the draw function ?

**Comment by pablomayobre** [comment]
Should be fairly cheap since it will only happen once per frame, but it will also depend on the number of entities
