### ISSUE TITLE
The sample code for Assemblages contains an extra parentheses ')'

### ISSUE THREAD

**Issue by trevinwong** [Keyslam-Group/Concord#58]
The current documentation for assemblages looks like this:

```
-- Make an Assemblage function
-- e is the Entity being assembled.
-- cuteness and legs are variables passed in
function animal(e, cuteness, legs)
    e
    :give(cutenessComponentClass, cuteness)
    :give(limbs, legs, 0) -- Variable amount of legs. 0 arm.
end)

-- Make an Assemblage that uses animal
-- cuteness is a variables passed in
function cat(e, cuteness)
    e
    :assemble(animal, cuteness * 2, 4) -- Cats are twice as cute, and have 4 legs.
    :give(soundComponent, "meow.mp3")
end)
```

Ofc this is just a small nitpick, but there is an extra ')' parentheses at the end of `end` on both functions `animal` and `cat`.

**Comment by pablomayobre** [comment]
You are right, this example is incorrect. This is gonna be tracked under https://github.com/Keyslam-Group/Concord/issues/35 and https://github.com/Keyslam-Group/Concord/issues/36

Thanks for the details, I'll keep them in mind as I fix the docs
