### ISSUE TITLE
Retrieve all components example incorrect

### ISSUE THREAD

**Issue by togfoxy** [Keyslam-Group/Concord#61]
This example should say:

```
-- Retrieve all Components
-- WARNING: Do not modify this table. It is read-only
local allComponents = myEntity:getComponents()

for ComponentClass, Component in pairs(allComponents) do
    -- Do stuff
end
```

The 'ipairs' should say 'pairs'

**Comment by pablomayobre** [comment]
Let me generalize this a bit, and say docs are outdated and incomplete. This is gonna be tracked under #35 and #36

Thanks for the details, I'll keep them in mind as I fix the docs
